#!/bin/bash

CURRENT_TAG=$(git describe --abbrev=0 --tags)
APP_NAME="msa_sdk"
VERSION_MIN=${CURRENT_TAG##*-}
VERSION=$(python -c "import msa_sdk; print(msa_sdk.VERSION)")
RELEASE=${VERSION_MIN}_$(date +%Y%m%d%H%M)

cp setup.cfg.template setup.cfg

RPM_HOME="/home/rpm"

pdoc3 --html --force -o msa_sdk/html msa_sdk

mkdir -p rpms/
docker run --rm -u rpm -v "$(pwd):${RPM_HOME}/build" \
    -w "${RPM_HOME}/build" rpm-build \
    python3 setup.py bdist_rpm --release="${RELEASE}" \
    --binary-only \
    --dist-dir rpms/

# clean
rm -rf build/ dist/ "${APP_NAME}_${VERSION}.egg-info"
rm setup.cfg
