#!/bin/bash

# RPM_BUILD="$(pwd)/rpmbuild"
# mkdir -p "${RPM_BUILD}"

VERSION='0.2'
RELEASE='0'

sed "s/{VERSION}/${VERSION}/" setup.py.template > setup.py

RPM_HOME="/home/rpm"

pdoc3 --html --force -o msa_sdk/html msa_sdk

# docker run --rm -u rpm -v "$(pwd)/rpmbuild:${RPM_HOME}/rpmbuild" \
docker run --rm -u rpm -v "$(pwd):${RPM_HOME}/build" \
    -w "${RPM_HOME}/build" rpm-build \
    python3 setup.py bdist_rpm --release="${RELEASE}" \
    --requires="python3-requests" \
    --binary-only \
    --dist-dir rpms/

mkdir -p rpms/
rm -rf build/ dist/ msa_sdk.egg-info/
