#!/bin/bash

set -x
set -e

CURRENT_TAG=$(git describe --abbrev=0 --tags --first-parent)
VERSION_ALL=${CURRENT_TAG##*_R}
VERSION_MAJ=${VERSION_ALL%-*}
VERSION_MIN=${VERSION_ALL##*-}


VERSION=$(python -c "import msa_sdk; print(msa_sdk.VERSION)")
RELEASE=${VERSION_MIN}_$(date +%Y%m%d%H%M)

if [ "$1" = "-r" ]; then
	RELEASE=$2
fi


RPM_BUILD="/home/rpm/build"
RPMS_DIR="rpms"
DOC_DIR="msa_sdk/html"


main() {
	mkdir -p ${RPMS_DIR}
	generate_doc
	generate_rpm

	rm -rf "${DOC_DIR}"
	rm -rf build/ dist/ msa_sdk.egg-info/
}

generate_doc() {
	docker_run "
	pdoc3 --html --force -o "${DOC_DIR}" msa_sdk
	"
}

generate_rpm() {
	docker_run "
	python3 setup.py bdist_rpm --release=${RELEASE} \
	--binary-only \
	--dist-dir ${RPMS_DIR}
	"
}

docker_run() {
	docker run \
	--rm \
	-e USER_ID=`id -u` \
	-v "$(pwd):${RPM_BUILD}" \
	-w "${RPM_BUILD}" \
	rpm-build \
	\
	$1
}


main
