#!/bin/bash


docker build -t rpm-build - <<EOT
FROM fedora:29

RUN yum -y groupinstall 'Development Tools'
RUN yum -y install fedora-packager libffi-devel zlib-devel
RUN yum -y remove yum-utils
RUN yum -y install yum-utils


RUN yum -y install sudo rsync php
RUN sed -i.bak -n -e '/^Defaults.*requiretty/ { s/^/# /;};/^%wheel.*ALL$/ { s/^/# / ;} ;/^#.*wheel.*NOPASSWD/ { s/^#[ ]*//;};p' /etc/sudoers

RUN yum install -y https://rdo.fedorapeople.org/rdo-release.rpm

RUN useradd -s /bin/bash -G adm,wheel,systemd-journal -m rpm

RUN yum clean all

RUN pip3 install pdoc3

EOT
