#!/bin/bash

usage() {
    echo './run_tests [normal|html|verbose|quiet]'
    exit 0
}

if [ -z "$1" ]; then
    usage
fi

PYTEST='python -m pytest --cov-report term-missing --disable-pytest-warnings --cov -x --no-cov-on-fail --cov-fail-under 100 --ff --isort --pydocstyle --ignore=required_pkgs'

case "$1" in
    'html')
        PYTEST="${PYTEST} --cov-report=html"
        ;;
    'verbose')
        PYTEST="${PYTEST} -v"
        ;;
    'quiet')
        PYTEST="${PYTEST} -q"
        ;;
    'normal')
        ;;
    '*')
        usage
        ;;
esac

# Run
$PYTEST
